# Change these first
owner: james-martinez # Your GitHub organization or username, where this repository lives
repo: levelup # The name of this repository

sites:
  - name: Code
    url: https://code.levelup.cce.af.mil
    __dangerous__insecure: true
  - name: Chat
    url: https://chat.levelup.cce.af.mil
    __dangerous__insecure: true
  - name: Jira
    url: https://jira.levelup.cce.af.mil
    __dangerous__insecure: true
  - name: Confluence
    url: https://confluence.levelup.cce.af.mil
    __dangerous__insecure: true
  - name: Keycloak
    url: https://keycloak.levelup.cce.af.mil/auth/realms/prod
    __dangerous__insecure: true
  - name: NIPRGPT
    url: https://chat.niprgpt.mil/
    __dangerous__insecure: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /levelup
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Levelup Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page of services from levelup.cce.af.mil
  navbar:
    - title: Status
      href: https://$OWNER.github.io/$REPO
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
